### ISSUE TITLE
Error: Couldn't posix_spawn: error 2

### ISSUE THREAD

**Issue by xit7** [sballin/alfred-search-notes-app#59]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Openning Alfred with keyboard shortcut immediately shows error. Worked like a charm since yesterday. Did not change anything to Alfred or setup since then.2. 

Hope you can help? Can't live without it :) 

**Error text**

search_notes error
lease copy this entire text if submitting an error report. You may need to scroll.

panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:461
main.main()
github.com/sballin/alfred-search-notes-app/main.go:474 +0x654

macOS: 12.3.1
Alfred: 4.6.4
Workflow: 3.5.2
CPU: arm64e
Binary xattrs: com.dropbox.attrs
Notes DB xattrs: 
Binary info: 0755 501/3y 20/staff
Notes DB info: 0644 501/3y 20/staff
Query: title ''
Accounts: iCloud

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: 12.3.1
 - CPU: Intel or Apple (M1)? M1
 - Alfred version: 4.6.4
 - Workflow version: How can I see this?
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? Yes, worked before
 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder?
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by xit7** [comment]
All right, got it. Although in Preferences there was no hint regarding Full Disk Access I figured this was missing. Enabled it (again), now all good.

Thanks!
