### ISSUE TITLE
Operation not permitted, Ventura 13.2.1

### ISSUE THREAD

**Issue by krasnyt** [sballin/alfred-search-notes-app#68]
Hello, I'm getting the following error pop up window when I try to search for any notes.

>  Please copy this entire text if submitting an error report. You may need to scroll.
> 
> panic: unable to open database file: operation not permitted
> 
> goroutine 1 [running]:
> main.PanicOnErr(...)
> github.com/sballin/alfred-search-notes-app/main.go:461
> main.main()
> github.com/sballin/alfred-search-notes-app/main.go:474 +0x654
> 
> macOS: 13.2.1
> Alfred: 5.0.6
> Workflow: 3.5.2
> CPU: arm64e
> Binary xattrs: com.apple.provenance
> Notes DB xattrs: 
> Binary info: 0755 501/tomas 20/staff
> Notes DB info: 0644 501/tomas 20/staff
> Query: title ''
> Accounts: Google, iCloud,

**Comment by krasnyt** [comment]
Reinstalling with newest version did not help. Also re-enabling the permission you mentioned did not help. Notes I am searching for are Apple notes. Always the same popup.

**Comment by sballin** [comment]
Ok, then it could be related to com.apple.provenance or the google account even being enabled in Notes.

**Comment by mpodlodowski** [comment]
Alfred 4, same issue

> panic: unable to open database file: operation not permitted
> 
> goroutine 1 [running]:
> main.PanicOnErr(...)
> github.com/sballin/alfred-search-notes-app/main.go:461
> main.main()
> github.com/sballin/alfred-search-notes-app/main.go:474 +0x654
> 
> macOS: 13.2
> Alfred: 4.8
> Workflow: 3.5.2
> CPU: arm64e
> Binary xattrs: 
> Notes DB xattrs: 
> Binary info: 0755 501/marcin 20/staff
> Notes DB info: 0644 501/marcin 20/staff
> Query: title ''
> Accounts: iCloud

**Comment by sballin** [comment]
The first time you run it, are you getting automatically prompted to give it the various permissions described in the readme?

**Comment by mpodlodowski** [comment]
I’m using Ventura for quite a long time already. It was my first time trying to use the workflow. Not sure if I was asked to grant permissions

**Comment by sballin** [comment]
If you have the Go compiler installed, you can try following the compile instructions here: https://github.com/sballin/alfred-search-notes-app#compile

**Comment by sballin** [comment]
Also it may be most important to disable/re-enable the full disk access permission for Alfred, as described in the readme.

**Comment by mpodlodowski** [comment]
Yes! Thank you @sballin, full disk access permission was not granted to my Alfred. Everything's fine now.
