### ISSUE TITLE
Just wont work.....

### ISSUE THREAD

**Issue by aidelank** [sballin/alfred-search-notes-app#73]
Please copy this entire text if submitting an error report. You may need to scroll.

panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:461
main.main()
github.com/sballin/alfred-search-notes-app/main.go:474 +0x654

macOS: 14.1.2
Alfred: 5.1.4
Workflow: 3.5.2
CPU: arm64e
Binary xattrs: com.apple.provenance
Notes DB xattrs: 
Binary info: 0755 501/lucas 20/staff
Notes DB info: 0644 501/lucas 20/staff
Query: title ''
Accounts: iCloud

**Comment by aidelank** [comment]
> You may need to disable/re-enable full disk access for Alfred: https://github.com/sballin/alfred-search-notes-app#required-permissions (worked in this thread: [#68 (comment)](https://github.com/sballin/alfred-search-notes-app/issues/68#issuecomment-1486501128))

Ah thank you! It worked!!
